# SPDX-FileCopyrightText: Copyright (c) 2009-2025 Yegor Bugayenko
# SPDX-License-Identifier: MIT

source 'https://rubygems.org'

gem 'csv', '>0'
gem 'jekyll', '~>4.4.0'
gem 'jekyll-plantuml', '~>1.5.0'
gem 'jekyll-press', '~>0.2.1'
gem 'jgd', '~>1.14.0'
gem 'kramdown', '~>2.5.1'
gem 'nokogiri', '~>1.19.0'
gem 'uuidtools', '~>3.0.0'
