assets:
  settings.xml: "yegor256/home#assets/rultor/settings.xml"
  pubring.gpg: "yegor256/home#assets/pubring.gpg"
  secring.gpg: "yegor256/home#assets/secring.gpg"
  id_rsa: "yegor256/home#assets/heroku-key"
  id_rsa.pub: "yegor256/home#assets/heroku-key.pub"
  s3cfg: "yegor256/home#assets/s3cfg"

env:
  MAVEN_OPTS: "-XX:MaxPermSize=256m -Xmx1g"

install: |
  sudo apt-get install bsdmainutils
  sudo gem install pdd
  cd src/bundle
  sudo bundle install
  cd ../..

deploy:
  script: |
    mvn clean package -Prultor --errors --settings ../settings.xml --batch-mode
    mvn clean
    pdd --source=$(pwd) --verbose --file=rultor.xml
    s3cmd --no-progress put rultor.xml --config=../s3cfg s3://pdd.teamed.io/rultor.xml

release:
  script: |
    mvn versions:set "-DnewVersion=${tag}"
    git commit -am "${tag}"
    cp ../settings.xml settings.xml
    mvn clean package -Pqulice -Prultor --errors --batch-mode
    git remote add heroku git@heroku.com:rultor.git
    mkdir ~/.ssh
    mv ../id_rsa ../id_rsa.pub ~/.ssh
    chmod -R 600 ~/.ssh/*
    echo -e "Host *\n  StrictHostKeyChecking no\n  UserKnownHostsFile=/dev/null" > ~/.ssh/config
    build=$(git rev-parse --short HEAD)
    sed -i "s/BUILD/${build}/g" src/main/resources/META-INF/MANIFEST.MF
    sed -i "s/BUILD/${build}/g" src/main/resources/log4j.properties
    git add src/main/resources/META-INF/MANIFEST.MF
    git add src/main/resources/log4j.properties
    git commit -m 'build number set'
    git add settings.xml
    git commit -m 'settings.xml'
    git fetch --unshallow
    git push -f heroku $(git symbolic-ref --short HEAD):master
    git reset HEAD~1
    curl -f --connect-timeout 15 --retry 5 --retry-delay 30 http://www.rultor.com
    mvn clean site-deploy -Psite --errors --settings ../settings.xml --batch-mode

merge:
  script: |
    mvn help:system clean package -Pqulice -Prultor --errors --settings ../settings.xml --batch-mode
    mvn clean site -Psite --errors --settings ../settings.xml --batch-mode
    mvn clean
    pdd --source=$(pwd) --verbose --file=/dev/null
