#
# Just run "bundle"
#
source 'https://rubygems.org'
gem 'jekyll', '3.1.0'
gem 'sass'
gem 'jekyll-sass'
gem 'jekyll-plantuml', '1.0.2'
gem 'jekyll-press'
gem 'jgd', '1.3'
gem 'nokogiri'
gem 'mail'
gem 'uuidtools'
gem 'liquid'
gem 'redcarpet'
